version: "3.3"
services:
  frontend:
    image: node:lts-alpine3.13
    container_name: frontend
    volumes:
      - ./app/frontend:/frontend
    working_dir: /frontend
    ports:
      - 3000:3000
    entrypoint: >
      sh -c "npm install
      && npm run build
      && npm start"

  backend:
    image: node:lts-alpine3.13
    container_name: backend
    env_file: ./docker.env
    volumes:
      - ./app/backend:/backend
    working_dir: /backend
    ports:
      - 3001:3001
    entrypoint: >
      sh -c "npm install
      && npm run build
      && ./node_modules/@nestjs/cli/bin/nest.js start -w"

  db:
    image: postgres:13.3-alpine
    container_name: db
    user: postgres
    env_file: ./docker.env
    volumes:
      - ./app/db:/db
    working_dir: /db
    ports:
      - 5432:5432
    entrypoint: sh -c "/db/init-user-db.sh; while true; do sleep 1; done;"
