version: "3.3"
services:
  frontend:
    image: node:lts-alpine3.13
    container_name: frontend
    volumes:
      - ./app/frontend:/frontend
    ports:
      - 3000:3000
    entrypoint: sh -c "while true; do sleep 1; done" #npm --prefix /frontend run dev

  backend:
    build: ./app/backend
    image: backend
    container_name: backend
    volumes:
      - ./app/backend:/backend
    ports:
      - 3001:3001
    entrypoint: sh -c "while true; do sleep 1; done" #sh -c "nest start -w"
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - ./data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
networks:
  postgres:
    driver: bridge

