version: "3.3"
services:
  frontend:
    image: node:lts-alpine3.13
    container_name: frontend
    volumes:
      - ./app/frontend:/frontend
    ports:
      - 3000:3000
    entrypoint: sh -c "while true; do sleep 1; done" #npm --prefix /frontend run dev

  backend:
    build: ./app/backend
    container_name: backend
    volumes:
      - ./app/backend/src:/backend/src
    ports:
      - 3001:3001
    entrypoint: sh -c "./node_modules/@nestjs/cli/bin/nest.js start -w"
  
  db:
    build: ./app/db
    container_name: db
    ports:
      - 5432:5432
    entrypoint: sh -c "while true; do sleep 1; done;" #pg_ctl -D . -l logfile start